app:
  upload-dir: "${user.home}/uploads/documents"
  base-url: "http://localhost:8080"
  jwt-secret: fWGy30lAyaSNRLLDq2Lau0LJHkruRPjYem1Jpnt3Q+c=
  jwt-expiration-time: 86400000
  cors:
    allowed-origins:
      - "http://149.56.110.16"
      - "http://localhost:3000"
      - "http://localhost:3001"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "PATCH"
      - "OPTIONS"
    allowed-headers:
      - "*"
    allow-credentials: true

server:
  port: 8080

spring:

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB


  application:
    name: CirculosEstudioBackend

  datasource:
    url: jdbc:postgresql://nozomi.proxy.rlwy.net:58053/railway
    username: postgres
    password: fZPodzylOicBKAdlwYfORXIIUcZDuWTJ
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
